version: "3.7"
services:
  fastapi:
    image: tiangolo/uvicorn-gunicorn-fastapi:latest
    command: uvicorn main:app --host 0.0.0.0:8000
    ports:
      - 8000:8000
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Q1w2e3r4t5
      - POSTGRES_DB=test_db
    depends_on:
      - fastapi
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=tirafen@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Q1w2e3r4t5
    ports:
      - "5050:80"
    depends_on:
      - db
  rabbitmq:
    image: rabbitmq:3.8
    container_name: rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
        RABBITMQ_DEFAULT_VHOST: /
    ports:
        - "5672:5672"
        - "15672:15672"
  celery:
    build: ./celery_app
    command: celery -A celery_app.tasks worker -l INFO --concurrency=2
    volumes:
      - .:/usr/src/celery_app
    links:
      - rabbitmq
      - db
    depends_on:
      - fastapi
      - rabbitmq
      - db
 
