version: "3.7"
services:
  fastapi:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8008:8000"
    expose:
      - "8000"
      - "8008"
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Q1w2e3r4t5
      - POSTGRES_DB=test_db
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=tirafen@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Q1w2e3r4t5
    ports:
      - "5050:80"
    expose:
      - "80"
    depends_on:
      - db
  rabbitmq:
    image: rabbitmq:3.8
    container_name: rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
        RABBITMQ_DEFAULT_VHOST: /
    ports:
        - "5672:5672"
        - "15672:15672"
    expose:
      - "15672"
      - "5672"
  celery:
    build: .
    command: celery -A celery_app.tasks worker -l INFO --concurrency=2
    volumes:
      - ./app:/celery_app
    links:
      - rabbitmq
      - db
    depends_on:
      - rabbitmq
      - db
  celery-beat:
    build: .
    command: celery -A celery_app.tasks beat
    volumes:
      - ./app:/celery_app
    links:
      - rabbitmq
      - db
    depends_on:
      - rabbitmq
      - db
  flower:
    build: .
    command: celery -A celery_app.tasks flower
    volumes:
      - ./app:/celery_app
    ports:
      - "5555:5555"
    depends_on:
      - celery
      - rabbitmq